name: Legit Workflow

on: [push, pull_request]
jobs:
  test:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: "shit"
      run: |
        echo "123"
        echo ${{ secrets.GITHUB_TOKEN }}
